### ISSUE TITLE
Can this be Real?

### ISSUE THREAD

**Issue by sgnoohc** [Moelf/FHist.jl#40]
https://github.com/Moelf/FHist.jl/blob/2ea9ea2036b416b96042b173751be3e69d2c4347/src/hist1d.jl#L129

I am having issues where I try to do something like

h.hist = Histogram(edges, bc)

and the ones being replaced is Real instead of Int and Histogram complains.

ERROR: MethodError: Cannot `convert` an object of type
  Histogram{Real,1,Tuple{StepRange{Int64{},Int64{}}}} to an object of type
  Histogram{Int64,1,Tuple{StepRange{Int64{},Int64{}}}}

I wonder if assuming "Real" is better than Int.

**Comment by aminnj** [comment]
Do you have a small example? If it were Real then that would allow Float64 counts, but there’s no way to get floats when filling without weights in that method

**Comment by sgnoohc** [comment]
using FHist
using StatsBase
h1 = Hist1D([1,2,3,4,5], 0:1:7)
h2 = Hist1D([2,3,4,5,6], 0:1:7)
a = [h1, h2]

# All three fails
# h1.hist = Histogram(binedges(h1), [0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0])
# a[1] = Hist1D(Histogram(binedges(h1), [0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]))
# a[1] = Hist1D(Histogram(binedges(h1), [0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]), [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])

I would have to construct an entirely new [] and replace the a as a whole.

**Comment by aminnj** [comment]
I would think this should indeed fail because you’re overriding the type of the struct from array of ints to array of floats. So IMO the Julian way must be to remake the whole struct as you say. But @Moelf is the expert…

**Comment by Moelf** [comment]
Right, so the reason line `129` is like that is because you can't get floating-point bin-count with that constructor (and `Real` is an abstract type -> reduced performance). Regarding the actual problem, the constrain really comes from:
```julia
a = [h1, h2]
```
change this to `Hist1D[h1, h2]` makes the last 2 examples work, because this tells Julia to not overly constrain the `eltype` of `a`.

In general, automatically promoting scalar is common:
```julia
julia> a = [1.2, 3.4];

julia> a[2] = 2;

julia> a
2-element Vector{Float64}:
 1.2
 2.0
```

We could teach histograms to promote automatically, but IMO they are too composite; silently doing too much may cause debug headache later. We could also always use `Float64` for bin counts, not sure what draw backs this implies but it's weird for sure.

**Comment by Moelf** [comment]
btw Julia types are generally "invariant":
```julia
julia> Int <: Real
true

julia> Vector{Int} <: Vector{Real}
false

julia> Hist1D{Int}
Hist1D{Int64}

julia> Hist1D{Int} <: Hist1D{Real}
false
```

Which means:
```julia
julia> a = Hist1D{Real}[];

julia> push!(a, Hist1D(Int; bins=1:3))
ERROR: MethodError: Cannot `convert` an object of type 
  Hist1D{Int64, Tuple{UnitRange{Int64}}} to an object of type 
  Hist1D{Real}
Closest candidates are:
```

**Comment by Moelf** [comment]
oops. Closed by accident, is there actionable item here?

**Comment by sgnoohc** [comment]
no. actionable item is on my end to write Hist1D[].
