### ISSUE TITLE
FHist type-parameter (of eltype) is also used for the weights

### ISSUE THREAD

**Issue by tamasgal** [Moelf/FHist.jl#61]
Not sure if this is a bug or feature, but I was confused when doing

```julia
using FHist

h = Hist1D(Float32, bins=0:0.5:1)
push!.(h, rand(100_000_000))
```

which produces wrong counts:

![Screenshot 2022-04-12 at 12 13 56](https://user-images.githubusercontent.com/1730350/162938135-65aba261-be04-42fb-bd71-67a4d096718b.png)

The counts are simply `h.hist.weights` but that should not depend on the element type.

I can of course fix it if it's a bug, but maybe I miss some design decision `;)`

**Comment by Moelf** [comment]
Yeah I guess weight should always be Float64?

**Comment by aminnj** [comment]
Is it just because of f32? https://meaningofstuff.blogspot.com/2014/09/when-float-does-not-change-when.html . I remember having this issue with TH1F's trying to fill very large MC samples :) 

I thought the `weights` in `h.hist.weights` is a misnomer -- it's just what StatsBase.Histogram calls the counts, so we'd have the same issue trying to do:
```
h = Hist1D(Int8, bins=0:0.5:1)
push!.(h, rand(10^3))
```

**Comment by tamasgal** [comment]
Yep, that's basically the problem, incrementing large floats. This eltype-weights coupling is a bit unfortunate for some other types too, as you demonstrated `;D`

I'd also say that the "weights" should be `Float64` or maybe even configurable. In my case I simply have event counts, so no floating point is required.

**Comment by aminnj** [comment]
But shouldn't the bin count storage type be specified up front (in the same way that we select TH1F/TH1D/...)? I think the type of the x-value and the true weight the user specifies during a `push!()` is decoupled from the bin count type: https://github.com/Moelf/FHist.jl/blob/c117818da7d7b17f2828d68b3daffaf4f42917e9/src/hist1d.jl#L108 Though of course there's some casting at the end in order to increment the bin counts

Actually it seems the default is Float64 when the count type is not specified:
```julia
julia> h = Hist1D(;bins=0:0.5:1);

julia> bincounts(h)
2-element Vector{Float64}:
 0.0
 0.0
```

**Comment by Moelf** [comment]
oh yeah I forgot `StatsBase` weight is actually bin count, yeah I agree with what @aminnj said, basically that parameter is like the `F` in `TH1F`, and I also think default to `Float64` is intended.

**Comment by Moelf** [comment]
>In my case I simply have event counts, so no floating point

use `Int` then, basically, `TH1I`?
